### ISSUE TITLE
tests\assets\corkami-poc-dataset\PE\bin\no_dd64.exe flagged as Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by Alan-Jowett** [trailofbits/pe-parse#171]
Microsoft Defender is flagging this test PE file as malware.

It might be worth double-checking that this is file is not malware.

**Comment by Alan-Jowett** [comment]
Thanks. I am currently following up with the Microsoft Defender team to understand why it's getting flagged. This was more as an FYI on the off chance this was real.

**Comment by woodruffw** [comment]
Gotcha, thanks for the heads up! Yeah, as best I can tell, this is a false positive. Here's what Binary Ninja shows me for the one function in the PE:

![Screen Shot 2022-05-12 at 11 35 22 AM](https://user-images.githubusercontent.com/3059210/168113491-1f5cda72-c9cc-445d-9a4f-f8a6e076de56.png)

That mostly looks like gibberish to me (it's popping into RBP instead of creating a stack frame?) and then calling whatever happens to be at that stack address, which is probably why it looks malicious.

Virustotal finds a bunch of mixed results: https://www.virustotal.com/gui/file/6a68f15b358267d78e6b2aed9e7e1ae2fc037a2c6635242a2afa9627ab2c02bd

**Comment by woodruffw** [comment]
No problem! Thanks for the diligence.
