### ISSUE TITLE
Segmentation fault parsing notepad.exe

### ISSUE THREAD

**Issue by roj4s** [trailofbits/pe-parse#23]
I'm trying to parse notepad.exe which is PE32+.

$file executables/notepad.exe 
executables/notepad.exe: PE32+ executable (GUI) x86-64, for MS Windows

Using the following code:

#include <iostream>
#include <sstream>
#include "parse.h"

using namespace std;

int main(void)
{
parsed_pe *p = ParsePEFromFile("executables/notepad.exe");
return 0;
}

gdb said:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f67be8f034d in std::string::push_back(char) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6

**Comment by secretsquirrel** [comment]
Confirmed.

**Comment by dguido** [comment]
@pgoodman Can you check this out when you get the chance?

**Comment by pgoodman** [comment]
@roj4s, can you upload notepad.exe?

**Comment by secretsquirrel** [comment]
@pgoodman I tested it with this https://live.sysinternals.com/tcpview.exe and other x64 pefiles and the error is the same each time.

I compiled it on ubuntu 16.04 with both g++ and clang++, same error.

**Comment by roj4s** [comment]
i took notepad.exe from a clean windows8 installation iso.

**Comment by pgoodman** [comment]
@secretsquirrel  Thanks for the link!
@roj4s Unfortunately I don't have windows 8 ;-)

**Comment by pgoodman** [comment]
I am not familiar with this codebase and decided to debug it without even trying to understand what the code was doing. Here was how I went about debugging this issue "blindly." 

First, I compiled the code with `-g3 -O0` so that I could get the most debug information out of the program while running in `undodb-gdb`.

The segfault happens at the end of `parse_resource_table` when executing `rde->lang_str.clear();`. The error is an invalid write (confirmed by Valgrind's memcheck tool). So, I started there.

At first I suspected a use-after-free of the `rde`, which has type `struct resource_dir_entry`. If the data of `rde` had been re-used, then the `std::string`s within it may have been corrupted, causing the segfault. To try to confirm this, I went and added a destructor to `struct resource_dir_entry`:
```C++
__attribute__((noinline, never_inline))
resource_dir_entry::~resource_dir_entry(void) {
  asm("int3;" ::: "memory");
}
```
I added the breakpoint on the line with the `asm` block, recompiled and re-ran the program. I never hit this breakpoint so that told me it wasn't a use-after-free, because a free of `resource_dir_entry` clearly never happened!

I then looked at the definition of the `rde` pointer itself. Not far after the definition, I saw a `memset(rde, 0, sizeof(*rde));`. This seemed like a bad idea; you can't be certain that zeroing out a `std::string` does the right thing. So, I changed that code to:
```c++
      rde->ID = 0;
      rde->RVA = 0;
      rde->type = 0;
      rde->name = 0;
      rde->lang = 0;
      //memset(rde, 0, sizeof(*rde));
```
Yay! Things worked :-D This is a bit ugly so I added a proper constructor and cleaned up the code a bit.
```C++
inline resource_dir_entry(void)
      : ID(0),
        RVA(0),
        type(0),
        name(0),
        lang(0) {}
```

**Comment by dguido** [comment]
Thanks @pgoodman!

**Comment by secretsquirrel** [comment]
@pgoodman Awesome work! Thanks!
