### ISSUE TITLE
Review code with clang-tidy

### ISSUE THREAD

**Issue by dguido** [trailofbits/pe-parse#36]

**Comment by jkolek** [comment]
Some of the common clang-tidy suggestions:

1. Range-based for loop
Use:
  for (auto s: secs) {
    ...
  }
instead of:
  for (list<section>::iterator sit = secs.begin(), e = secs.end();
       sit != e; ++sit) {
    section s = *sit;
    ...
  }

2. Redundant boolean literals
Use:
  if (!readWord(data, id, len))
instead of:
  if (readWord(data, id, len) == false)

3. Use static_cast instead of C-style casts.

4. Use nullptr instead of NULL.

5. Implicit casts
For example, change:
  if (!rdt.NameEntries)
to:
  if (rdt.NameEntries == 0u)

and change:
  if (!dirent)
to:
  if (dirent == nullptr)

**Comment by jkolek** [comment]
Should I make these changes?

**Comment by dguido** [comment]
Sure, just make a separate PR for it.

**Comment by dguido** [comment]
Note that PR #40 refers to this issue.
